# TT_Vision monocular model

Camera:
  name: "TT_Vision monocular"
  setup: "monocular"
  model: "perspective"

  fx: 643.0669220754221
  fy: 643.3892680728896
  cx: 640.8965046836516
  cy: 363.44238771193847

  k1: -0.034643738563733845
  k2: 0.028118963147165027
  p1: 0.00048742415927187604
  p2: -0.0003729749435374049
  k3: 0.0

  fps: 30.0
  cols: 1280
  rows: 720

  color_order: "RGB"

Preprocessing:
  min_size: 800

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 30
  min_fast_threshold: 12

Mapping:
  backend: "g2o"
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20
  erase_temporal_keyframes: false
  num_temporal_keyframes: 15

Tracking:
  backend: "g2o"
  enable_temporal_keyframe_only_tracking: false

KeyframeInserter:
  wait_for_local_bundle_adjustment: false

Relocalizer:
  search_neighbor: true

LoopDetector:
  backend: "g2o"

System:
  map_format: "msgpack"
  num_grid_cols: 47
  num_grid_rows: 30

PangolinViewer:
  keyframe_size: 0.07
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.65
  viewpoint_z: -1.9
  viewpoint_f: 400
